// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { ERC1155Holder$Type } from "./ERC1155Holder";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ERC1155Holder"]: ERC1155Holder$Type;
    ["@openzeppelin/contracts/token/ERC1155/utils/ERC1155Holder.sol:ERC1155Holder"]: ERC1155Holder$Type;
  }

  interface ContractTypesMap {
    ["ERC1155Holder"]: GetContractReturnType<ERC1155Holder$Type["abi"]>;
    ["@openzeppelin/contracts/token/ERC1155/utils/ERC1155Holder.sol:ERC1155Holder"]: GetContractReturnType<ERC1155Holder$Type["abi"]>;
  }
}
