// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { ERC721Holder$Type } from "./ERC721Holder";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ERC721Holder"]: ERC721Holder$Type;
    ["@openzeppelin/contracts/token/ERC721/utils/ERC721Holder.sol:ERC721Holder"]: ERC721Holder$Type;
  }

  interface ContractTypesMap {
    ["ERC721Holder"]: GetContractReturnType<ERC721Holder$Type["abi"]>;
    ["@openzeppelin/contracts/token/ERC721/utils/ERC721Holder.sol:ERC721Holder"]: GetContractReturnType<ERC721Holder$Type["abi"]>;
  }
}
