// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { Auctions$Type } from "./Auctions";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["Auctions"]: Auctions$Type;
    ["contracts/Auctions.sol:Auctions"]: Auctions$Type;
  }

  interface ContractTypesMap {
    ["Auctions"]: GetContractReturnType<Auctions$Type["abi"]>;
    ["contracts/Auctions.sol:Auctions"]: GetContractReturnType<Auctions$Type["abi"]>;
  }
}
